package PF_ExceptionHandlerForward;

import org.apache.beehive.netui.pageflow.PageFlowController;
import org.apache.beehive.netui.pageflow.Forward;
import org.apache.beehive.netui.pageflow.ActionNotFoundException;
import org.apache.beehive.netui.pageflow.annotations.Jpf;

/**
 *******************************************************************************
 *
 * @desc: This test contains one action method, begin and 3 exception handler methods
 * all that have a forward that has the same name, "gotoError".  There should be
 * no conflict between the begin method and the exception handler methods but
 * the 3 exception handlers should not be allowed.

    see http://issues.apache.org/jira/browse/BEEHIVE-288?page=comments#action_59050
    i have changed the path for the duplicate forwards to have different paths.
    so, this is just the name collision.

 *
 * @result: The compiler should catch this and issue an error(s).
 *
 ******************************************************************************/

    @Jpf.Controller(
        catches = {
            @Jpf.Catch(
                type = java.lang.NoSuchFieldException.class,
                method = "handleIt1"),
            @Jpf.Catch(
                type = java.lang.IllegalArgumentException.class,
                method = "handleIt2"),
            @Jpf.Catch(
                type = java.lang.IllegalAccessException.class,
                method = "handleIt3")
        })
public class Controller extends PageFlowController
   {

    @Jpf.Action(
        forwards = {
            @Jpf.Forward(
                name = "gotoError",
                path = "Pg1.jsp")
        })
   public Forward begin()
      {
      return new Forward("gotoError");
      }

    @Jpf.ExceptionHandler(
        forwards = {
            @Jpf.Forward(
                name = "gotoError",
                path = "Pg1.jsp")
        })
   protected Forward handleIt1(java.lang.NoSuchFieldException ex, String actionName,
                               String message, Object form)
      {
      return new Forward("gotoError");
      }

    @Jpf.ExceptionHandler(
        forwards = {
            @Jpf.Forward(
                name = "gotoError", 
		path="Pg2.jsp")
        })
   protected Forward handleIt2(java.lang.IllegalArgumentException ex, String actionName,
                               String message, Object form)
      {
      return new Forward("gotoError");
      }

    @Jpf.ExceptionHandler(
        forwards = {
            @Jpf.Forward(
                name = "gotoError", 
		path="Pg3.jsp")
        })
   protected Forward handleIt3(java.lang.IllegalAccessException ex, String actionName,
                               String message, Object form)
      {
      return new Forward("gotoError");
      }
   }
